from datetime import *
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from databricks.sdk.runtime import *
from dateutil.relativedelta import WE, relativedelta

from de_databricks.common.utils import *


### Reminder Email for Inactive Users
def remind_inactive_users(env, url, recipient_email, inactive_date):
    inactive_date = inactive_date.strftime("%B %d, %Y")
    html_body = f"""
    <html>
    <head>
        <style>
            .container {{
                line-height: 1.6;
                color: #333;
                padding: 20px;
                border: 1px solid #ccc;
                border-radius: 10px;
                width: 600px;
                margin: 0 auto;
            }}
            .header {{
                background-color: #f7f7f7;
                padding: 10px 0;
                text-align: center;
                border-bottom: 1px solid #ccc;
            }}
            .header h1 {{
                margin: 0;
                font-size: 24px;
            }}
            .content p {{
                margin: 10px 0;
            }}
        </style>
    </head>
    <body>
        <div class ="container">
            <div class = "header"> 
                <h1>{env} Databricks Inactive Account Notice</h1>
            </div>
            <div class = "content">
                <p>Dear User,</p>
                <br />
                <p>&nbsp; &nbsp;Please be informed that your Databricks user account on the GovTech Data Platform - {env} environment will become inactive on <strong>{inactive_date}</strong>. Inactive accounts will be flagged for deactivation within 7 days. In addition, all tables and volumes under your ownership will subsequently be removed.</p>
                <p>&nbsp; &nbsp;Please note the following effects of account deactivation:
                    <li>Your account cannot authenticate or access the Databricks UI or APIs.</li>
                    <li>Applications or scripts that use tokens generated by your account are no longer able to access the Databricks API.</li>
                    <li>Scheduled jobs created by your account will fail unless they are assigned to a new owner.</li>
                <p>&nbsp; &nbsp;If you would like to retain your account and the assets under your ownership, you may do so by logging in to the {env} environment via this <a href={url}>link</a> and your account will remain active.
                <p>&nbsp; &nbsp;For more information regarding the GovTech Data Platform, you may refer to our CDO Portal on <a href="https://gccprod.sharepoint.com/sites/GOVTECH-intranet/cdo/SitePages/Databricks.aspx">ONESpace</a>. If you have any further questions, please feel free to reach out to the GovTech CDO team at CDO@tech.gov.sg.</p>
                <br />
                <p>Thank you.</p>
                <p>GovTech Chief Data Office</p>
            </div>
        </div>
    </body>
    </html>
    """
    from_email = '"GovTech Data Platform" <no-reply@data.tech.gov.sg>'
    subject = f"{env} Databricks Inactive Account Reminder"
    send_email(from_email, subject, html_body, to_emails=recipient_email)


### Notification Email for Deletion of Inactive Users
def notify_inactive_users(env, url, bcc_emails, future_date=None):
    if not future_date:
        future_date = (datetime.now() + relativedelta(months=1)).replace(day=1) + relativedelta(
            day=1, weekday=WE(1)
        )
    deactivation_date = future_date.strftime("%B %d, %Y")
    html_body = f"""
    <html>
    <head>
        <style>
            .container {{
                line-height: 1.6;
                color: #333;
                padding: 20px;
                border: 1px solid #ccc;
                border-radius: 10px;
                width: 600px;
                margin: 0 auto;
            }}
            .header {{
                background-color: #f7f7f7;
                padding: 10px 0;
                text-align: center;
                border-bottom: 1px solid #ccc;
            }}
            .header h1 {{
                margin: 0;
                font-size: 24px;
            }}
            .content p {{
                margin: 10px 0;
            }}
        </style>
    </head>
    <body>
        <div class ="container">
            <div class = "header"> 
                <h1>{env} Databricks Account Removal Notice</h1>
            </div>
            <div class = "content">
                <p>Dear User,</p>
                <br />
                <p>&nbsp; &nbsp;Please be informed that your Databricks user account will be deactivated on the GovTech Data Platform {env} environment on <strong>{deactivation_date}</strong> as your last login was more than 90 days ago. In addition, all tables and volumes under your ownership will subsequently be removed.</p>
                <p>&nbsp; &nbsp;If you would like to retain your account and the assets under your ownership, you may do so by logging in to the {env} environment via this <a href={url}>link</a> and your account will remain active.
                <p>&nbsp; &nbsp;For more information regarding the GovTech Data Platform, you may refer to our CDO Portal on <a href="https://gccprod.sharepoint.com/sites/GOVTECH-intranet/cdo/SitePages/Databricks.aspx">ONESpace</a>. If you have any further questions, please feel free to reach out to the GovTech CDO team at CDO@tech.gov.sg.</p>
                <br />
                <p>Thank you.</p>
                <p>GovTech Chief Data Office</p>
            </div>
        </div>
    </body>
    </html>
    """
    from_email = '"GovTech Data Platform" <no-reply@data.tech.gov.sg>'
    subject = f"{env} Databricks Account Removal Notice"
    send_email(from_email, subject, html_body, bcc_emails=bcc_emails, blind_email=True)


### Email Report after notifications have been sent out
def email_admin_report(env, emails_list, admin_emails, action):
    # Construct the table
    user_html = """<table style="border-collapse: collapse; width: 100%; margin: 10px 0; font-size: 13px;">
                        <tr>
                            <th style="border: 1px solid #ddd; padding: 8px 12px; text-align: left; background-color: #f8f8f8;">Username</th>"""
    if action == "Inactive Account":
        user_html += """<th style="border: 1px solid #ddd; padding: 8px 12px; text-align: left; background-color: #f8f8f8;">Last Action</th>
                        <th style="border: 1px solid #ddd; padding: 8px 12px; text-align: left; background-color: #f8f8f8;">Days Left</th>"""
    user_html += "</tr>"

    # Iterate over list of users
    for user in emails_list:
        user_html += f"""
                        <tr>
                            <td style="border: 1px solid #ddd; padding: 8px 12px; text-align: left;">{user["email"]}</td>"""
        if action == "Inactive Account":
            user_la = user["last_action"].strftime("%d %b %Y")
            user_html += f"""<td style="border: 1px solid #ddd; padding: 8px 12px; text-align: left;">{user_la}</td>
                             <td style="border: 1px solid #ddd; padding: 8px 12px; text-align: left;">{user["days_left"]}</td>"""
        user_html += "</tr>"
    user_html += "</table>"

    # Construct the HTML body with the tables for the user
    html_body = f"""
        <html>
        <head>
            <style>
            .container {{
                line-height: 1.6;
                color: #333;
                padding: 20px;
                border: 1px solid #ccc;
                border-radius: 10px;
                width: 600px;
                margin: 0 auto;
            }}
            .header {{
                background-color: #f7f7f7;
                padding: 10px 0;
                text-align: center;
                border-bottom: 1px solid #ccc;
            }}
            .header h1 {{
                margin: 0;
                font-size: 24px;
            }}
            .content p {{
                margin: 10px 0;
            }}
            ul {{
                list-style-type: disc;
                padding-left: 20px;
                margin: 0;
            }}
            li {{
                word-wrap: break-word;
                work-bread: break-all;
                overflow-wrap: break-word;
                padding: 5px 0;
                margin: 0;
            }}
        </style>
    </head>
        <body>
            <div class ="container">
                <div class = "header"> 
                    <h1>Databricks {env} {action}</h1><br />
                    <h1>Notification Report</h1>
                </div>
                <div class = "content">
                    <p>Dear Admin,</p>
                    <br />
                    <p>Please see the list of users below for the {action} notification emails:</p>
                    {user_html} 
                    <br />
                    <p>Thank you.</p>   
                    <p>GovTech Chief Data Office</p>
            </div>
        </div>
        </body>
        </html>
    """
    from_email = '"GovTech Data Platform" <no-reply@data.tech.gov.sg>'
    subject = f"{env} Databricks Email Report"
    send_email(from_email, subject, html_body, to_emails=admin_emails)
