terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
    time = {
      source  = "hashicorp/time"
      version = "~> 0.9"
    }
  }
}

locals {
  is_workspace = var.purpose == "workspace"
  bucket_name  = coalesce(var.bucket_name_override, "sst-s3-gvt-sdp-databricks-${var.env}-${var.purpose}")
}

# ── S3 bucket ────────────────────────────────────────────────────
resource "aws_s3_bucket" "sdp_s3_bucket" {
  count  = var.skip_bucket_creation ? 0 : 1
  bucket = local.bucket_name

  tags = {
    Name        = local.bucket_name
    Environment = var.env
    Purpose     = var.purpose
  }
}

# ── Server-side encryption with CMK ─────────────────────────────
# Only created when var.kms_key_arn is provided. If omitted, S3 falls back
# to SSE-S3 (AWS-managed keys), which is encrypted but gives you no key control.
#
# bucket_key_enabled = true is important for cost:
#   Without it, every S3 PUT and GET makes a separate KMS API call.
#   With it, S3 derives a short-lived bucket-level key from your CMK and uses
#   that locally — reducing KMS API calls (and their cost) by ~99%.
#   The CMK still controls access; the bucket key is just a performance optimisation.
resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  count  = !var.skip_bucket_creation && var.enable_kms ? 1 : 0
  bucket = aws_s3_bucket.sdp_s3_bucket[0].id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = var.kms_key_arn
    }
    bucket_key_enabled = true
  }
}

# ── Cross-Account IAM role ─────────────────────────────────────────────────────
# For workspace buckets the external_id is var.databricks_account_id, known upfront.
# For UC buckets the role is first created with placeholder external_id "0000";
# null_resource.update_uc_trust_policy then updates it with the real external_id
# generated by databricks_storage_credential — all in a single apply.
resource "aws_iam_role" "unity_catalog" {
  name = var.iam_role_name

  assume_role_policy = local.is_workspace ? jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::414351767826:root" }
      Action    = "sts:AssumeRole"
      Condition = {
        StringEquals = { "sts:ExternalId" = var.databricks_account_id }
      }
    }]
    }) : jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL" }
      Action    = "sts:AssumeRole"
      Condition = {
        StringEquals = { "sts:ExternalId" = "0000" }
      }
    }]
    # Self-assume and real external_id are added by null_resource.update_uc_trust_policy
    # after databricks_storage_credential is created and generates the real external_id.
  })

  # The null_resource.update_uc_trust_policy manages the real trust policy after creation.
  # Ignore drift here to prevent Terraform from reverting it back to the placeholder on every apply.
  lifecycle {
    ignore_changes = [assume_role_policy]
  }
}

# ── S3 access policy ─────────────────────────────────────────────
resource "aws_iam_policy" "s3_access" {
  name        = "${var.iam_role_name}-s3-access"
  description = "Grants read/write access to ${local.bucket_name}"

  lifecycle {
    ignore_changes = [description]
  }

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = concat(
      [{
        Effect = "Allow"
        Action = local.is_workspace ? [
          "s3:GetObject",
          "s3:GetObjectVersion",
          "s3:PutObject",
          "s3:DeleteObject",
          "s3:ListBucket",
          "s3:GetBucketLocation",
          ] : [
          "s3:GetObject",
          "s3:PutObject",
          "s3:DeleteObject",
          "s3:ListBucket",
          "s3:GetBucketLocation",
          "s3:ListBucketMultipartUploads",
          "s3:ListMultipartUploadParts",
          "s3:AbortMultipartUpload",
        ]
        Resource = [
          "arn:aws:s3:::${local.bucket_name}/*",
          "arn:aws:s3:::${local.bucket_name}",
        ]
      }],
      # Self-assume permission — only needed for UC roles (non-workspace)
      local.is_workspace ? [] : [{
        Effect   = "Allow"
        Action   = ["sts:AssumeRole"]
        Resource = ["arn:aws:iam::${var.aws_account_id}:role/${var.iam_role_name}"]
      }],
      var.kms_key_arn != null ? [{
        Effect   = "Allow"
        Action   = ["kms:Decrypt", "kms:Encrypt", "kms:GenerateDataKey*"]
        Resource = [var.kms_key_arn]
      }] : []
    )
  })
}

# ── File events policy (SQS / SNS) ───────────────────────────────
# Required for Auto Loader file notification mode. Databricks manages SQS/SNS
# resources under the csms-* prefix; this grants permission for it to do so.
# Enable via var.enable_file_events = true (landing bucket only).
resource "aws_iam_policy" "file_events" {
  count = var.enable_file_events ? 1 : 0

  name        = "${var.iam_role_name}-file-events"
  description = "Allows Databricks Auto Loader to manage SQS/SNS file event notifications for ${local.bucket_name}"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "Setup"
        Effect = "Allow"
        Action = [
          "s3:GetBucketNotification",
          "s3:PutBucketNotification",
          "sns:ListSubscriptionsByTopic",
          "sns:GetTopicAttributes",
          "sns:SetTopicAttributes",
          "sns:CreateTopic",
          "sns:TagResource",
          "sns:Publish",
          "sns:Subscribe",
          "sqs:CreateQueue",
          "sqs:SendMessage",
          "sqs:GetQueueUrl",
          "sqs:GetQueueAttributes",
          "sqs:SetQueueAttributes",
          "sqs:TagQueue",
        ]
        Resource = [
          "arn:aws:s3:::${local.bucket_name}",
          "arn:aws:sqs:*:*:csms-*",
          "arn:aws:sns:*:*:csms-*",
        ]
      },
      {
        Sid    = "Consume"
        Effect = "Allow"
        Action = [
          "sqs:ReceiveMessage",
          "sqs:DeleteMessage",
          "sqs:ChangeMessageVisibility",
          "sqs:ListQueues",
          "sqs:ListQueueTags",
        ]
        Resource = ["arn:aws:sqs:*:*:csms-*"]
      },
      {
        Sid    = "Teardown"
        Effect = "Allow"
        Action = [
          "sns:DeleteTopic",
          "sns:Unsubscribe",
          "sqs:PurgeQueue",
          "sqs:DeleteQueue",
        ]
        Resource = [
          "arn:aws:sqs:*:*:csms-*",
          "arn:aws:sns:*:*:csms-*",
        ]
      },
    ]
  })
}

# ── Attach policies to the role ───────────────────────────────────
resource "aws_iam_role_policy_attachment" "s3_access" {
  role       = aws_iam_role.unity_catalog.name
  policy_arn = aws_iam_policy.s3_access.arn
}

resource "aws_iam_role_policy_attachment" "file_events" {
  count = var.enable_file_events ? 1 : 0

  role       = aws_iam_role.unity_catalog.name
  policy_arn = aws_iam_policy.file_events[0].arn
}

# ── Workspace bucket policy ───────────────────────────────────────
# Grants the Databricks production AWS account access to the workspace root
# bucket. The DatabricksAccountId condition scopes this to your specific
# Databricks account when var.databricks_account_id is provided.
resource "aws_s3_bucket_policy" "workspace" {
  count  = local.is_workspace && !var.skip_bucket_creation ? 1 : 0
  bucket = aws_s3_bucket.sdp_s3_bucket[0].id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { AWS = "arn:aws:iam::414351767826:root" }
      Action = [
        "s3:GetObject",
        "s3:GetObjectVersion",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListBucket",
        "s3:GetBucketLocation",
      ]
      Resource = [
        "arn:aws:s3:::${local.bucket_name}/*",
        "arn:aws:s3:::${local.bucket_name}",
      ]
      Condition = {
        StringEquals = {
          "aws:PrincipalTag/DatabricksAccountId" = concat([var.databricks_account_id], var.trusted_databricks_account_ids)
        }
      }
    }]
  })
}

# ── Unity Catalog resources (non-workspace only) ──────────────────
resource "databricks_storage_credential" "this" {
  count = local.is_workspace ? 0 : 1

  name    = var.storage_credential_name
  comment = "Storage credential for S3 external location: ${local.bucket_name}"

  aws_iam_role {
    role_arn = "arn:aws:iam::${var.aws_account_id}:role/${var.iam_role_name}"
  }
  skip_validation = true
  read_only       = var.read_only
  depends_on      = [aws_iam_role_policy_attachment.s3_access]
}

resource "time_sleep" "wait_for_iam_propagation" {
  count           = local.is_workspace ? 0 : 1
  create_duration = "30s"
  depends_on      = [null_resource.update_uc_trust_policy]
}

resource "databricks_external_location" "this" {
  count = local.is_workspace ? 0 : 1

  name            = var.external_location_name
  url             = "s3://${local.bucket_name}"
  credential_name = databricks_storage_credential.this[0].name
  comment         = "External location for ${local.bucket_name}"
  read_only       = var.read_only

  depends_on = [time_sleep.wait_for_iam_propagation]
}

# ── Optional Unity Catalog catalogs ──────────────────────────────
resource "databricks_catalog" "this" {
  for_each = var.catalogs

  name          = each.key
  storage_root  = "s3://${local.bucket_name}/${each.value.subdir}"
  owner         = each.value.owner
  force_destroy = true

  depends_on = [databricks_external_location.this]
}

# ── Update UC role trust policy with real external ID ────────────
# Databricks generates the real external_id only after the storage credential
# is created. This null_resource runs post-credential and calls the AWS CLI
# to replace the "0000" placeholder in the trust policy with the real value.
# Re-runs automatically if the external_id ever changes.
resource "null_resource" "update_uc_trust_policy" {
  count = local.is_workspace ? 0 : 1

  triggers = {
    external_id = databricks_storage_credential.this[0].aws_iam_role[0].external_id
  }

  provisioner "local-exec" {
    command = "aws iam update-assume-role-policy --role-name ${var.iam_role_name} --policy-document \"$POLICY\""
    environment = {
      POLICY = jsonencode({
        Version = "2012-10-17"
        Statement = [{
          Effect = "Allow"
          Principal = {
            AWS = [
              "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL",
              "arn:aws:iam::${var.aws_account_id}:role/${var.iam_role_name}"
            ]
          }
          Action = "sts:AssumeRole"
          Condition = {
            StringEquals = {
              "sts:ExternalId" = databricks_storage_credential.this[0].aws_iam_role[0].external_id
            }
          }
        }]
      })
    }
  }

  depends_on = [databricks_storage_credential.this]
}

# ── Update workspace role trust policy for additional trusted accounts ────────
# The workspace role's trust policy is created with a single ExternalId
# (var.databricks_account_id). When trusted_databricks_account_ids is non-empty,
# this null_resource patches the policy to add one statement per extra account.
# Uses the same ignore_changes workaround as the UC role update above.
resource "null_resource" "update_workspace_trust_policy" {
  count = local.is_workspace && length(var.trusted_databricks_account_ids) > 0 ? 1 : 0

  triggers = {
    trusted_ids = join(",", sort(var.trusted_databricks_account_ids))
  }

  provisioner "local-exec" {
    command = "aws iam update-assume-role-policy --role-name ${var.iam_role_name} --policy-document \"$POLICY\""
    environment = {
      POLICY = jsonencode({
        Version = "2012-10-17"
        Statement = concat(
          [{
            Effect    = "Allow"
            Principal = { AWS = "arn:aws:iam::414351767826:root" }
            Action    = "sts:AssumeRole"
            Condition = {
              StringEquals = { "sts:ExternalId" = var.databricks_account_id }
            }
          }],
          [for id in var.trusted_databricks_account_ids : {
            Effect    = "Allow"
            Principal = { AWS = "arn:aws:iam::414351767826:root" }
            Action    = "sts:AssumeRole"
            Condition = {
              StringEquals = { "sts:ExternalId" = id }
            }
          }],
          # NEW: UCMasterRole + self-assume for Unity Catalog access
          [{
            Effect = "Allow"
            Principal = {
              AWS = [
                "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL",
                "arn:aws:iam::${var.aws_account_id}:role/${var.iam_role_name}"
              ]
            }
            Action = "sts:AssumeRole"
          }]
        )
      })
    }
  }

  depends_on = [aws_iam_role.unity_catalog]
}

# ── Grants on the external location ──────────────────────────────
resource "databricks_grants" "external_location" {
  count = !local.is_workspace && length(var.external_location_grants) > 0 ? 1 : 0

  external_location = databricks_external_location.this[0].id

  dynamic "grant" {
    for_each = var.external_location_grants
    content {
      principal  = grant.key
      privileges = grant.value
    }
  }
}
