output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = aws_s3_bucket.sdp_s3_bucket.bucket
}

output "bucket_arn" {
  description = "ARN of the S3 bucket"
  value       = aws_s3_bucket.sdp_s3_bucket.arn
}

output "iam_role_arn" {
  description = "ARN of the IAM role created for Unity Catalog or workspace cross-account access"
  value       = aws_iam_role.unity_catalog.arn
}

output "storage_credential_id" {
  description = "ID of the Databricks storage credential. Empty string for workspace buckets."
  value       = local.is_workspace ? "" : databricks_storage_credential.this[0].id
}

output "external_location_url" {
  description = "S3 URL of the external location. Empty string for workspace buckets."
  value       = local.is_workspace ? "" : databricks_external_location.this[0].url
}

output "catalog_names" {
  description = "Map of catalog name → storage root URL for all catalogs created by this module. Empty map if none were created."
  value       = { for k, v in databricks_catalog.this : k => v.storage_root }
}

output "external_id" {
  description = "External ID generated by Databricks for the storage credential. Use this to update the IAM role trust policy on the second terraform apply. Empty for workspace buckets."
  value       = local.is_workspace ? "" : databricks_storage_credential.this[0].aws_iam_role[0].external_id
  sensitive   = true
}
